# Basic configuration file

OPENAI_API_KEY = '<YOUR_API_KEY>'
TELEGRAM_TOKEN = '<YOUR_TELEGRAM_TOKEN>'

keep_history = true
debug = false

[openai]
model = 'gpt-3.5-turbo'
temperature = 0.7
max_tokens = 2046
top_p = 1
frequency_penalty = 0.0
presence_penalty = 0.6
