name: Enforce the PEP8 style guide

on:
  push:
    branches:
      - main

jobs:
  autopep8:

    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install autopep8
      - name: Fix code formatting issues automatically
        run: |
          FIXES=$(autopep8 --diff --in-place --aggressive --aggressive .)

          if [[ -n $FIXES ]]; then
            echo "The following changes were made:"
            echo "$FIXES"

            git config --global user.name 'Daniel Dias'
            git config --global user.email 'lupeke@users.noreply.github.com'

            git commit -am "apply autopep8 formatting fixes"
            git push
          else
            echo "No autopep8 changes to apply."
          fi
